/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TableChartCovid {
        "rowsPerPage": number;
        "theme": {
            chartColors: string[];
        };
    }
}
declare global {
    interface HTMLTableChartCovidElement extends Components.TableChartCovid, HTMLStencilElement {
    }
    var HTMLTableChartCovidElement: {
        prototype: HTMLTableChartCovidElement;
        new (): HTMLTableChartCovidElement;
    };
    interface HTMLElementTagNameMap {
        "table-chart-covid": HTMLTableChartCovidElement;
    }
}
declare namespace LocalJSX {
    interface TableChartCovid {
        "rowsPerPage"?: number;
        "theme"?: {
            chartColors: string[];
        };
    }
    interface IntrinsicElements {
        "table-chart-covid": TableChartCovid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "table-chart-covid": LocalJSX.TableChartCovid & JSXBase.HTMLAttributes<HTMLTableChartCovidElement>;
        }
    }
}
